### ISSUE TITLE
@conda-forge-admin please update version

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/pyodide-build-feedstock#18]

**Comment by agriyakhetarpal** [comment]
Hi @bollwyvl, could you please re-trigger the version update? The release has been fixed and uploaded, now: https://pypi.org/project/pyodide-build/0.29.0/

**Comment by agriyakhetarpal** [comment]
Also, would it be alright if Hood, Gyeongjae, and I could join you as recipe maintainers for this feedstock?

**Comment by bollwyvl** [comment]
Of course! :rocket: :unicorn:

I'll do a manual PR once the PyPI sdist is up, and for the forms to be observed, would probably need comments by the interested parties there to confirm the change.

**Comment by bollwyvl** [comment]
This version is updated. Still awaiting additional issues/PRs for maintainers.
